version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=zyhua
    volumes:
      - $PWD/grafana_db:/var/lib/grafana grafana/grafana
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

#  consignment-service:
#    build: ./consignment-server
#    ports:
#      - 50051:50051
#    environment:
#      MICRO_ADRESS: ":50051"
#      MICRO_REGISTRY: "mdns"
#      DB_HOST: "datastore:27017"
