LogPath: ./log/access.log
JwtAuthSecret: zyhua
PidPath: pid
ServerAddr: :127.0.0.1:4001
EtcdAddr: 127.0.0.1:2379
ZipkinAddr: 127.0.0.1:9411

Redis:
  Host: 118.24.103.174
  Port: 6300
  Password: zyhua1122
  MaxIdle: 30
  MaxActive: 30

