global:
  scrape_interval: 15s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 10s # is set to the global default (10s).
  external_labels:
    monitor: 'blog-svr-monitor'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics' # defaults to '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'local'

  - job_name: 'user_space'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.0.1:4002']
        labels:
          group: 'arithmetic'
