LogPath: ./log/access.log
JwtAuthSecret: zyhua
PidPath: pid
ServerAddr: 127.0.0.1:4002
EtcdAddr: 127.0.0.1:2379
Prefix: /svc/user

Mysql:
  Username: webtest
  Password: zyhuatest
  Host: 127.0.0.1
  Port: 2333
  AuthSource: user
