version: '3'

services:
  etcd-svc:
    image: gcr.io/etcd-development/etcd:v3.3
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - ./data/etcd:/etcd-data
    environment:
      ETCD_NAME: node-01
      ETCD_DATA_DIR: /etcd-data
      ## 用于客户端访问
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ## 用于节点间通信
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380 
      ## 告诉集群中其他节点, 当前节点(node-01)的client地址(需要其他节点可以访问到). 逗号分隔
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379 
      ## 告诉集群中其他节点, 当前节点(node-01)的client地址(需要其他节点可以访问到). 逗号分隔
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://0.0.0.0:2380 
      ETCD_INITIAL_CLUSTER: node-01=http://0.0.0.0:2380

  server1:
    image: gokit-lorem-consul-03
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/github.com/generals-space/gokit/06.gokit-playground-example/63.gokit-lorem-etcd
    environment:
      SERVER_ADDR: server1
      SERVER_PORT: "8080"
      ETCD_URL: etcd-svc:2379
      ETCD_PREFIX: /lorem/
    command: ["go", "run", "server/main.go"]

  server2:
    image: gokit-lorem-consul-03
    ports:
      - 8081:8080
    volumes:
      - .:/go/src/github.com/generals-space/gokit/06.gokit-playground-example/63.gokit-lorem-etcd
    environment:
      SERVER_ADDR: server2
      SERVER_PORT: "8080"
      ETCD_URL: etcd-svc:2379
      ETCD_PREFIX: /lorem/
    command: ["go", "run", "server/main.go"]

  client:
    image: gokit-lorem-consul-03
    ports:
      - 8090:8080
    volumes:
      - .:/go/src/github.com/generals-space/gokit/06.gokit-playground-example/63.gokit-lorem-etcd
    environment:
      SERVER_ADDR: ## 留空
      SERVER_PORT: "8080"
      ETCD_URL: etcd-svc:2379
      ETCD_PREFIX: /lorem/
    command: ["go", "run", "client/main.go"]
